### ISSUE TITLE
Please remove my code from your wiki

### ISSUE THREAD

**Issue by alexmidd** [jvraines/WeirdCalendars#2] opened 2024-12-16 02:35 UTC
I have for some reason been blocked from viewing the “What date is it?” page on your wiki at Calendars.fandom, which I have been following, including the inclusion of some of my calendars on it (I am the person with the internet moniker “Timey” and have my own web pages at Time-Meddler.co.uk which feature my calendars. The code seems to have been picked from my web pages and used here, which I did not mind until I got blocked. Therefore could you now remove the code from your site? The files concerned are: 

NewCelticCalendar.cs
NewColognyCalendar.cs
OldEnglishLunarCalendar.cs
OldEnglishSolarCalendar.cs

If you could remove and stop using this code, alternatively unblock me as I have done nothing wrong.

Thanks 

Alex Middleton (Timey)

**Comment by jvraines** [comment] 2024-12-16 02:54
Dear Mr. Middleton,

I am sorry to hear of the difficulty you are experiencing. I assure you
that I have no administrative role at calendars.fandom.com and I have no
power to block anyone. Perhaps if you explain what you are experiencing
there, I can offer some help.

I assume you are aware that "What Date Is It?" includes not only a credit
to you personally, but also a hyperlink to your web site. It would be a
shame to deprive Fandom users of that information and you of that
promotion, don't you think?

Looking forward to resolving this situation to our mutual benefit,
Vincent Raines

**Comment by alexmidd** [comment] 2024-12-16 03:01
Hi Vincent

Thanks for your reply. To be honest I am quite happy for the code to remain but I just can’t work out why I am being blocked, or who to contact to resolve it. When I try to refresh the “What Date Is It?” page I get the following on screen:

Your user name or IP address has been blocked.

The block was made by Fandom Staff.

Reason given: This IP address is prevented from editing across the entire FANDOM network due to vandalism or other disruption by you or by someone who shares your IP address.
If you believe this is in error, please [contact FANDOM](https://calendars.fandom.com/wiki/Special:Contact).
The blocker also gave this additional reason: Violating Fandom's ToU.

Start of block: 19:06, 6 December 2024
Expiry of block: 19:06, 6 March 2025
Intended blockee:
Block ID: #1236234
Current IP address: 104.28.40.156
You may contact Fandom Staff to discuss the block. Please include all of the details above in any queries you make.

Finding appropriate Fandom Staff to contact is practically impossible. But I am also at a loss as to what I am supposed to have done. All I use the site for is to check my and other people’s calendars every few days to keep tabs on all the different dates, which is interesting. So, I’m not sure how this can be resolved, but it’s very frustrating indeed.

Alex
![IMG_0007](https://github.com/user-attachments/assets/b768bed6-ef0a-48fc-a9db-c94e78fa4072)

**Comment by jvraines** [comment] 2024-12-16 03:23
Thank you for the additional information, Alex. The first thing I usually
try is to delete site cookies; clear all fandom.com cookies from your web
browser and try again.

If you are still blocked, is anyone else connected to your ISP gateway?
Hosts on the same LAN or WiFi usually share the same IP address. Is it
possible someone else on your network did something naughty at Fandom.com?

Are you by any chance known as User 1N15ABCY at Fandom? The calendars wiki
has had a lot of robotic/empty pages created by that user this year and I
wouldn't be surprised if the Fandom staff detected and blocked it.

Finally, it could simply be a case of human and/or machine error, in which
case you must connect with a person at Fandom to resolve it. The only way
to do that is at Submit a request – Fandom
<https://support.fandom.com/hc/en-us/requests/new>.

Let me know what happens.

**Comment by alexmidd** [comment] 2024-12-16 10:35
Sorry, I meant to say that the account I set up had the username alexmidd, so I don’t recognise that username quoted.

Also, I have just tried to refresh the page on my MacBook, and it works fine, as it does on my Android phone, so it seems to be something to do with the iPad. 🤷‍♂️I am IT literate, but this sort of thing can be very confusing.

Anyway, thanks for the help so far. I will wait and see what I get back from Fandom.

Alex

Alex Middleton

**Comment by jvraines** [comment] 2024-12-16 16:47
Have you confirmed that your iPad is connecting to the same LAN or WiFi as
your phone and MacBook?

**Comment by alexmidd** [comment] 2024-12-16 18:45
Hi

Well, that’s interesting. Because all my devices are indeed using the same wifi/LAN. However, the iPad was coming up with a different IP address from the other devices. Turns out I had Apple iCloud Private Relay turned on.

Now this is a perfectly legitimate means of protection while surfing the web. However, I turned it off and tried the page refresh again (several times) and it now works OK. I’m not sure why but whatever block was put on there did not like the IP address used by that VPN.

I’m not sure what this means for whether I continue to use it or not but at least it seems to be some kind of explanation for what’s going on.

Alex

Alex Middleton

**Comment by jvraines** [comment] 2024-12-16 20:12
Glad you found the source of the problem, Alex. I understand that some
internet services are blocking Private Relay entirely because of the
potential for abuse. Perhaps the admins at Fandom will tell you if they
have adopted such a policy.

**Closed** 2024-12-19 19:34 UTC
